version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"

volumes:
  db_data: